spring:
  application:
    name: journalApp

  data:
    mongodb:
      database: journaldb
      uri: "mongodb+srv://shivam:shivam%40123@cluster0.ez2svpu.mongodb.net/?appName=Cluster0"
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: shivamsaini6013@gmail.com
    password: ddbfkajlazkfqemg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable : true





server:
  port: 8080
#  servlet:
#    context-path: /journal

weather:
  api:
    key: 6eb74d2cfcb4c8de74f67a46f875d20d



  redis:
    uri:redis-cli -u redis://default:rsOShSJQz7vlkt4c46mnXZ48WtycpD60@sago-time-reclaimed-22341.db.redis.io:17261
